$('.owl-carousel').owlCarousel({
  loop:true,
  margin:15,
  nav:false,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:3
      },
      1000:{
          items:5
      }
  },
    items:4,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true
});